use_frameworks!

platform :ios, '8.0'

target 'PodsA_Example' do
  pod 'PodsA', :path => '../'

  target 'PodsA_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
